from pyspark.sql.types import *


schema = StructType([
    StructField('event_id', StringType(), True),
    StructField('type', StringType(), True),
    StructField('context', StructType([
        StructField('title', StringType(), True),
        StructField('page_url', StringType(), True),
        StructField('canonical_url', StringType(), True),
        StructField('referrer', StringType(), True),
        StructField('user_agent', StringType(), True),
        StructField('device', StructType([
            StructField('vendor', StringType(), True),
            StructField('model', StringType(), True),
            StructField('type', StringType(), True)
        ]), True),
        StructField('operating_system', StructType([
            StructField('name', StringType(), True),
            StructField('version', StringType(), True)
        ]), True),
        StructField('browser', StructType([
            StructField('name', StringType(), True),
            StructField('version', StringType(), True),
            StructField('major', StringType(), True)
        ]), True),
        StructField('amp_version', StringType(), True),
        StructField('website_country', StringType(), True),
        StructField('country', StringType(), True),
        StructField('ip_address', StringType(), True),
    ]), True),
    StructField('user', StructType([
        StructField('user_id', StringType(), True),
        StructField('anonymous_id', StringType(), True),
        StructField('amp_id', StringType(), True),
        StructField('experiments', StringType(), True),
    ]), True),
    StructField('body', StructType([
        StructField('event_name', StringType(), True),
        StructField('data', StructType([
            StructField('title', StringType(), True),
            StructField('status', StringType(), True),
            StructField('page_url', StringType(), True),
            StructField('email_id', StringType(), True),
            StructField('form_type', StringType(), True),
            StructField('username', StringType(), True),
            StructField('sort_order',StringType(),True),
            StructField('sort_field_name',StringType(),True),
            StructField('page_path',StringType(),True),
            StructField('auth_status',StringType(),True),
            StructField('type',StringType(),True),
            StructField('cta_type',StringType(),True),
            StructField('product_id',StringType(),True),
            StructField('product_name',StringType(),True),
            StructField('provider_id',StringType(),True),
            StructField('list_position',StringType(),True),
            StructField('is_sponsored',StringType(),True),
            StructField('additional_parameters',
                StructType([
                    StructField('original_price', StringType(), True),
                    StructField('discounted_price',StringType(),True)
                ]),True),
            StructField('event_type',StringType(),True),
            StructField('object_clicked',StringType(),True),
            StructField('borrow_amount',StringType(),True),
            StructField('loan_duration_in_years',StringType(),True),
            StructField('citizenship',StringType(),True),
            StructField('is_recommended',StringType(),True),
            StructField('question_number',StringType(),True),
            StructField('question_answer',StringType(),True),
            StructField('loan_type',StringType(),True),
            StructField('property_type',StringType(),True),
            StructField('remaining_loan',StringType(),True),
            StructField('current_rate',StringType(),True),
            StructField('remaining_tenure',StringType(),True),
            StructField('current_bank',StringType(),True),
            StructField('rate_type',StringType(),True),
            StructField('loan_tenure',StringType(),True),
            StructField('is_paid',StringType(),True),
            StructField('action',StringType(),True),
            StructField('form_step',StringType(),True),
            StructField('form_name',StringType(),True),
            StructField('car_make',StringType(),True),
            StructField('ncd',StringType(),True),
            StructField('gender',StringType(),True),
            StructField('birthdate',StringType(),True),
            StructField('policy_expiring',StringType(),True),
            StructField('age',StringType(),True),
            StructField('filters',
                StructType([
                    StructField('0',StringType(),True),
                    StructField('1',StringType(),True),
                    StructField('2',StringType(),True),
                    StructField('3',StringType(),True),
                    StructField('4',StringType(),True),
                    StructField('type',StringType(),True),
                    StructField('location',StringType(),True),
                    StructField('start_date',StringType(),True),
                    StructField('end_date',StringType(),True),
                    StructField('adults',StringType(),True),
                    StructField('children',StringType(),True),
                    StructField('insurer',StringType(),True),
                    StructField('name',StringType(),True),
                    StructField('cover',StringType(),True),
                    StructField('covered',StringType(),True),
                    StructField('product_category',StringType(),True),
                    StructField('provider_name',StringType(),True)
                ]),True),
            StructField('language',StringType(),True),
            StructField('provider',StringType(),True),
            StructField('product_category',StringType(),True),
            StructField('page_type',StringType(),True),
            StructField('country', StringType(), True),
            StructField('channel', StringType(), True),
            StructField('product',StringType(),True),
            StructField('search',StringType(),True),
            StructField('affiliate_widget_type',StringType(),True),
            StructField('affiliate_category',StringType(),True),
            StructField('affiliate_page_type',StringType(),True),
            StructField('affiliate_location',StringType(),True),
            StructField('source',StringType(),True),
            StructField('source_id',StringType(),True),
            StructField('login_method',StringType(),True),
            StructField('product_category_id',StringType(),True),
            StructField('sequence',StringType(),True),
            StructField('filter_type',StringType(),True),
            StructField('page_referrer',StringType(),True),
            StructField('filter_step',StringType(),True)
        ]), True)
    ]), True),
    StructField('sent_at', StringType(), True),
    StructField('received_at', StringType(), True),
    StructField('version', StringType(), True),
])
